<style>
.fsizerDocs {
    font-family: font-family: system-ui;
    font-size:16px;
    padding: 1rem 0;
    /*width: 960px;*/
    max-width: 100%;
}
.i_block {
    text-indent: 30px;
}
.i_block_more {
    text-indent: 60px;
}
.docImage {
    /*text-indent: 30px;*/
    width:50vw;
    border:1px solid #000;
    margin:10px;
}
</style>
        
    </head>
    
    <div class="fsizerDocs">
<h3 style="margin-bottom:5px;text-decoration: underline;">Default Block</h3>
<div class="i_block">
The default Block is ID: 1. (ID: 1 cannot be deleted)</div>
<div class="i_block">
At setup, no categories will have selected a Furnace Sizer and will have the default value ID: 1;</div>
<br>
<h3 style="margin-bottom:5px; text-decoration: underline;">Inheritance</h3>
<br>
    <div class="docImage">
       <img alt="img1" src="<?= $escaper->escapeHtml($block->
            getViewFileUrl('Ecommerce121_Fsizer::images/Fsizer1.png')); ?>"/>
    </div>
    <div class="docImage">
       <img alt="img2" src="<?= $escaper->escapeHtml($block->
            getViewFileUrl('Ecommerce121_Fsizer::images/Fsizer2.png')); ?>"/>
    </div>
    <div class="docImage">
       <img alt="img3" src="<?= $escaper->escapeHtml($block->
            getViewFileUrl('Ecommerce121_Fsizer::images/Fsizer3.png')); ?>"/>
    </div>
    <div class="docImage">
       <img alt="img4" src="<?= $escaper->escapeHtml($block->
            getViewFileUrl('Ecommerce121_Fsizer::images/Fsizer4.png')); ?>"/>
    </div>
    <div class="docImage">
       <img alt="img5" src="<?= $escaper->escapeHtml($block->
            getViewFileUrl('Ecommerce121_Fsizer::images/Fsizer5.png')); ?>"/>
    </div>
    <div class="docImage">
       <img alt="img6" src="<?= $escaper->escapeHtml($block->
            getViewFileUrl('Ecommerce121_Fsizer::images/Fsizer6.png')); ?>"/>
    </div>
            
</div>   